# Use the official Nginx image as a base
FROM nginx:alpine

# Copy all the frontend files (HTML, CSS, JS) to Nginx's default directory
COPY . /usr/share/nginx/html

# Expose port 80 for the Nginx server
EXPOSE 80
