networks:
  project_network:
    driver: bridge

services:
  database:
    image: johnguinness/movie_posters_database:1.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - project_network

  backend:
    image: johnguinness/movie_posters_backend:1.0
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: project_db
    networks:
      - project_network

  frontend:
    image: johnguinness/movie_posters_frontend:1.0
    container_name: html_frontend
    ports:
      - "80:80"
    networks:
      - project_network