insert into project_db.genres (genre_id, genre_name) values (1, 'Comedy');
insert into project_db.genres (genre_id, genre_name) values (2, 'Horror');
insert into project_db.genres (genre_id, genre_name) values (3, 'Teen Fantasy');
insert into project_db.genres (genre_id, genre_name) values (4, 'Adventure');
insert into project_db.genres (genre_id, genre_name) values (5, 'Family');
insert into project_db.genres (genre_id, genre_name) values (6, 'Fantasy');
insert into project_db.genres (genre_id, genre_name) values (7, 'Holiday');
insert into project_db.genres (genre_id, genre_name) values (8, 'Period Drama');
insert into project_db.genres (genre_id, genre_name) values (9, 'Showbiz Drama');
insert into project_db.genres (genre_id, genre_name) values (10, 'Drama');
insert into project_db.genres (genre_id, genre_name) values (11, 'Epic');
insert into project_db.genres (genre_id, genre_name) values (12, 'Psychological Drama');
insert into project_db.genres (genre_id, genre_name) values (13, 'Tragedy');
insert into project_db.genres (genre_id, genre_name) values (14, 'Dark Comedy');
insert into project_db.genres (genre_id, genre_name) values (15, 'Gun Fu');
insert into project_db.genres (genre_id, genre_name) values (16, 'Raunchy Comedy');
insert into project_db.genres (genre_id, genre_name) values (17, 'Superhero');
insert into project_db.genres (genre_id, genre_name) values (18, 'Time Travel');
insert into project_db.genres (genre_id, genre_name) values (19, 'Action');
insert into project_db.genres (genre_id, genre_name) values (20, 'Sci-Fi');
insert into project_db.genres (genre_id, genre_name) values (21, 'Action Epic');
insert into project_db.genres (genre_id, genre_name) values (22, 'One-Person Army Action');
insert into project_db.genres (genre_id, genre_name) values (23, 'Crime');
insert into project_db.genres (genre_id, genre_name) values (24, 'Thriller');
insert into project_db.genres (genre_id, genre_name) values (25, 'Sword & Sandal');
insert into project_db.genres (genre_id, genre_name) values (26, 'Coming-of-Age');
insert into project_db.genres (genre_id, genre_name) values (27, 'Teen Drama');
insert into project_db.genres (genre_id, genre_name) values (28, 'Sci-Fi Epic');
insert into project_db.genres (genre_id, genre_name) values (29, 'Space Sci-Fi');
insert into project_db.genres (genre_id, genre_name) values (30, 'Satire');
insert into project_db.genres (genre_id, genre_name) values (31, 'Historical Epic');
insert into project_db.genres (genre_id, genre_name) values (32, 'War Epic');
insert into project_db.genres (genre_id, genre_name) values (33, 'History');
insert into project_db.genres (genre_id, genre_name) values (34, 'War');
insert into project_db.genres (genre_id, genre_name) values (35, 'Splatter Horror');
insert into project_db.genres (genre_id, genre_name) values (36, 'Mystery');
insert into project_db.genres (genre_id, genre_name) values (37, 'Legal Drama');
insert into project_db.genres (genre_id, genre_name) values (38, 'Dystopian Sci-Fi');
insert into project_db.genres (genre_id, genre_name) values (39, 'Contemporary Western');
insert into project_db.genres (genre_id, genre_name) values (40, 'Heist');
insert into project_db.genres (genre_id, genre_name) values (41, 'Police Procedural');
insert into project_db.genres (genre_id, genre_name) values (42, 'Western');
insert into project_db.genres (genre_id, genre_name) values (43, 'Baseball');
insert into project_db.genres (genre_id, genre_name) values (44, 'Docudrama');
insert into project_db.genres (genre_id, genre_name) values (45, 'Biography');
insert into project_db.genres (genre_id, genre_name) values (46, 'Sport');
insert into project_db.genres (genre_id, genre_name) values (47, 'Mockumentary');
insert into project_db.genres (genre_id, genre_name) values (48, 'Supernatural Horror');
insert into project_db.genres (genre_id, genre_name) values (49, 'Vampire Horror');
insert into project_db.genres (genre_id, genre_name) values (50, 'Conspiracy Thriller');
insert into project_db.genres (genre_id, genre_name) values (51, 'Cyber Thriller');
insert into project_db.genres (genre_id, genre_name) values (52, 'Cyberpunk');
insert into project_db.genres (genre_id, genre_name) values (53, 'Psychological Thriller');
insert into project_db.genres (genre_id, genre_name) values (54, 'Suspense Mystery');
insert into project_db.genres (genre_id, genre_name) values (55, 'Fairy Tale');
insert into project_db.genres (genre_id, genre_name) values (56, 'Fantasy Epic');
insert into project_db.genres (genre_id, genre_name) values (57, 'Feel-Good Romance');
insert into project_db.genres (genre_id, genre_name) values (58, 'Quest');
insert into project_db.genres (genre_id, genre_name) values (59, 'Romantic Epic');
insert into project_db.genres (genre_id, genre_name) values (60, 'Swashbuckler');
insert into project_db.genres (genre_id, genre_name) values (61, 'Romance');
insert into project_db.genres (genre_id, genre_name) values (62, 'Animal Adventure');
insert into project_db.genres (genre_id, genre_name) values (63, 'Computer Animation');
insert into project_db.genres (genre_id, genre_name) values (64, 'Kung Fu');
insert into project_db.genres (genre_id, genre_name) values (65, 'Martial Arts');
insert into project_db.genres (genre_id, genre_name) values (66, 'Wuxia');
insert into project_db.genres (genre_id, genre_name) values (67, 'Animation');
insert into project_db.genres (genre_id, genre_name) values (68, 'Psychological Horror');
insert into project_db.genres (genre_id, genre_name) values (69, 'Adventure Epic');
insert into project_db.genres (genre_id, genre_name) values (70, 'Dark Fantasy');
insert into project_db.genres (genre_id, genre_name) values (71, 'Whodunnit');
insert into project_db.genres (genre_id, genre_name) values (72, 'Romantic Comedy');
insert into project_db.genres (genre_id, genre_name) values (73, 'Screwball Comedy');
insert into project_db.genres (genre_id, genre_name) values (74, 'Road Trip');
insert into project_db.genres (genre_id, genre_name) values (75, 'Supernatural Fantasy');
insert into project_db.genres (genre_id, genre_name) values (76, 'Urban Adventure');
insert into project_db.genres (genre_id, genre_name) values (77, 'Cop Drama');
insert into project_db.genres (genre_id, genre_name) values (78, 'Drug Crime');
insert into project_db.genres (genre_id, genre_name) values (79, 'Artificial Intelligence');
insert into project_db.genres (genre_id, genre_name) values (80, 'Quirky Comedy');
insert into project_db.genres (genre_id, genre_name) values (81, 'Anime');
insert into project_db.genres (genre_id, genre_name) values (82, 'Iyashikei');
insert into project_db.genres (genre_id, genre_name) values (83, 'Sea Adventure');
insert into project_db.genres (genre_id, genre_name) values (84, 'Teen Comedy');
insert into project_db.genres (genre_id, genre_name) values (85, 'Steamy Romance');
insert into project_db.genres (genre_id, genre_name) values (86, 'Farce');
insert into project_db.genres (genre_id, genre_name) values (87, 'Political Drama');
insert into project_db.genres (genre_id, genre_name) values (88, 'Medical Drama');
insert into project_db.genres (genre_id, genre_name) values (89, 'Globetrotting Adventure');
insert into project_db.genres (genre_id, genre_name) values (90, 'Stop Motion Animation');
insert into project_db.genres (genre_id, genre_name) values (91, 'Music');
insert into project_db.genres (genre_id, genre_name) values (92, 'Buddy Comedy');
insert into project_db.genres (genre_id, genre_name) values (93, 'Spy');
insert into project_db.genres (genre_id, genre_name) values (94, 'High-Concept Comedy');
insert into project_db.genres (genre_id, genre_name) values (95, 'Holiday Comedy');
insert into project_db.genres (genre_id, genre_name) values (96, 'Holiday Family');
insert into project_db.genres (genre_id, genre_name) values (97, 'Slapstick');
insert into project_db.genres (genre_id, genre_name) values (98, 'Survival');
insert into project_db.genres (genre_id, genre_name) values (99, 'Serial Killer');
insert into project_db.genres (genre_id, genre_name) values (100, 'True Crime');
insert into project_db.genres (genre_id, genre_name) values (101, 'Sword & Sorcery');
insert into project_db.genres (genre_id, genre_name) values (102, 'Teen Adventure');
insert into project_db.genres (genre_id, genre_name) values (103, 'Legal Thriller');
insert into project_db.genres (genre_id, genre_name) values (104, 'Parody');
insert into project_db.genres (genre_id, genre_name) values (105, 'Dinosaur Adventure');
insert into project_db.genres (genre_id, genre_name) values (106, 'Kaiju');
insert into project_db.genres (genre_id, genre_name) values (107, 'Monster Horror');
insert into project_db.genres (genre_id, genre_name) values (108, 'B-Horror');
insert into project_db.genres (genre_id, genre_name) values (109, 'Slasher Horror');
insert into project_db.genres (genre_id, genre_name) values (110, 'Teen Horror');
insert into project_db.genres (genre_id, genre_name) values (111, 'Caper');
insert into project_db.genres (genre_id, genre_name) values (112, 'Tragic Romance');
insert into project_db.genres (genre_id, genre_name) values (113, 'Political Thriller');
insert into project_db.genres (genre_id, genre_name) values (114, 'Gangster');
insert into project_db.genres (genre_id, genre_name) values (115, 'Erotic Thriller');
insert into project_db.genres (genre_id, genre_name) values (116, 'Pop Musical');
insert into project_db.genres (genre_id, genre_name) values (117, 'Teen Romance');
insert into project_db.genres (genre_id, genre_name) values (118, 'Prison Drama');
insert into project_db.genres (genre_id, genre_name) values (119, 'Disaster');
insert into project_db.genres (genre_id, genre_name) values (120, 'Adult Animation');
insert into project_db.genres (genre_id, genre_name) values (121, 'Hand-Drawn Animation');
insert into project_db.genres (genre_id, genre_name) values (122, 'Workplace Drama');
insert into project_db.genres (genre_id, genre_name) values (123, 'Motorsport');
insert into project_db.genres (genre_id, genre_name) values (124, 'Body Swap Comedy');
insert into project_db.genres (genre_id, genre_name) values (125, 'Costume Drama');
insert into project_db.genres (genre_id, genre_name) values (126, 'Classical Western');
insert into project_db.genres (genre_id, genre_name) values (127, 'Dark Romance');
insert into project_db.genres (genre_id, genre_name) values (128, 'Financial Drama');
insert into project_db.genres (genre_id, genre_name) values (129, 'Classic Musical');
insert into project_db.genres (genre_id, genre_name) values (130, 'Musical');
insert into project_db.genres (genre_id, genre_name) values (131, 'Samurai');
insert into project_db.genres (genre_id, genre_name) values (132, 'Zombie Horror');
insert into project_db.genres (genre_id, genre_name) values (133, 'Mountain Adventure');
insert into project_db.genres (genre_id, genre_name) values (134, 'Jungle Adventure');
insert into project_db.genres (genre_id, genre_name) values (135, 'Film Noir');
insert into project_db.genres (genre_id, genre_name) values (136, 'Alien Invasion');
insert into project_db.genres (genre_id, genre_name) values (137, 'Body Horror');
insert into project_db.genres (genre_id, genre_name) values (138, 'Rock Musical');
insert into project_db.genres (genre_id, genre_name) values (139, 'Western Epic');
insert into project_db.genres (genre_id, genre_name) values (140, 'Steampunk');
insert into project_db.genres (genre_id, genre_name) values (141, 'Holiday Romance');
insert into project_db.genres (genre_id, genre_name) values (142, 'Car Action');
insert into project_db.genres (genre_id, genre_name) values (143, 'Korean Drama');
insert into project_db.genres (genre_id, genre_name) values (144, 'Cozy Mystery');
insert into project_db.genres (genre_id, genre_name) values (145, 'Football');
insert into project_db.genres (genre_id, genre_name) values (146, 'Desert Adventure');
insert into project_db.genres (genre_id, genre_name) values (147, 'Boxing');
insert into project_db.genres (genre_id, genre_name) values (148, 'Extreme Sport');
insert into project_db.genres (genre_id, genre_name) values (149, 'Slice of Life');
insert into project_db.genres (genre_id, genre_name) values (150, 'Seinen');
insert into project_db.genres (genre_id, genre_name) values (151, 'Holiday Animation');
insert into project_db.genres (genre_id, genre_name) values (152, 'Spaghetti Western');
insert into project_db.genres (genre_id, genre_name) values (153, 'Hard-boiled Detective');
insert into project_db.genres (genre_id, genre_name) values (154, 'Mecha');
insert into project_db.genres (genre_id, genre_name) values (155, 'Stoner Comedy');
insert into project_db.genres (genre_id, genre_name) values (156, 'Shōnen');
insert into project_db.genres (genre_id, genre_name) values (157, 'Folk Horror');
insert into project_db.genres (genre_id, genre_name) values (158, 'Sketch Comedy');
insert into project_db.genres (genre_id, genre_name) values (159, 'Bumbling Detective');
insert into project_db.genres (genre_id, genre_name) values (160, 'Jukebox Musical');
insert into project_db.genres (genre_id, genre_name) values (161, 'Shōjo');
